### ISSUE TITLE
In-progress analysis screen is hard to read.

### ISSUE THREAD

**Issue by shurcooL** [bradleyfalzon/gopherci#104]
When a GopherCI analysis is running (in-progress), this is what the page shows:

![image](https://user-images.githubusercontent.com/1924134/28733535-a192f394-73aa-11e7-93a4-a685b3b2e89f.png)

When it finishes, it may look like this:

![image](https://user-images.githubusercontent.com/1924134/28733551-af421f38-73aa-11e7-93df-79fd5fee2488.png)

Unless one is intimately familiar with GopherCI peculiarities (as I am now, since I'm reporting this issue with details), up until the analysis finishes, it's very hard to know/see that it's actually in progress.

There's no progress spinner, and there's no "In-progress" badge on the in-progress page.

I don't think a spinner is needed, but at least having a badge would help tremendously. E.g.:

![image](https://user-images.githubusercontent.com/1924134/28733723-76b38566-73ab-11e7-8c70-3bf8d69d4551.png)

Also note the little touch of making it say "0 issues found **so far...**".

**Comment by bradleyfalzon** [comment]
Yeah I saw this the other day too, I'm surprised I released it like this.

Definitely a bug and that looks like a clear solution, thanks I'll implement this.
