### ISSUE TITLE
https://gci.gopherci.io/ is 404, doesn't seem to be intentional.

### ISSUE THREAD

**Issue by shurcooL** [bradleyfalzon/gopherci#120]
Steps to reproduce:

1. Start by reading the comment `gopherci` bot posted at https://github.com/shurcooL/issuesapp/commit/f6765859b855f5da5a01552c186048cf6047e80e#commitcomment-23646403:

    > GopherCI found 1 issue in the last 3 commits, see: https://gci.gopherci.io/analysis/925

2. Click on https://gci.gopherci.io/analysis/925.

3. Click on "GopherCI" text in header:

    ![image](https://user-images.githubusercontent.com/1924134/29302016-840127ae-814e-11e7-9d3b-e1e8e694efc1.png)

4. End up at https://gci.gopherci.io/, which is currently 404:

    ![image](https://user-images.githubusercontent.com/1924134/29302029-aad834f8-814e-11e7-8ba3-8267cc6131ed.png)

This doesn't appear to be intentional, which is why I'm reporting it.

**Comment by bradleyfalzon** [comment]
No it's not intentional maybe one day it can be a place for #17, but until then will fix.
