### ISSUE TITLE
Update Go version to 1.10.

### ISSUE THREAD

**Issue by dmitshur** [bradleyfalzon/gopherci#130]
Go 1.10 has been released by now:

https://blog.golang.org/go1.10

GopherCI should be updated to use the latest stable version of Go. Some things (like GopherJS) require it, and it causes build failures otherwise (e.g, see https://gci.gopherci.io/analysis/1386).

**Comment by bradleyfalzon** [comment]
Thanks, merged, it's building now: https://hub.docker.com/r/gopherci/gopherci-env/builds/

**Comment by bradleyfalzon** [comment]
Build finished, it'll be deployed in the next 30 minutes automatically (I can't check the status from where I am unfortunately).

**Comment by bradleyfalzon** [comment]
Thanks @shurcooL, much appreciated.

**Comment by dmitshur** [comment]
Thank you!

**Comment by bradleyfalzon** [comment]
36 minutes ago the updated image was pulled down.
