### ISSUE TITLE
Support checking repository on push to branch (not via PR)

### ISSUE THREAD

**Issue by bradleyfalzon** [bradleyfalzon/gopherci#27]
Owners can push directly to master/other branches:

- We need the permissions and workflow figured out before a release is public, as it's not clear exactly how to add more permissions to an integration at a later stage.
- Note many people would push to their repository then make a PR, this workflow should ideally not cause GopherCI to run on push and then on PR creation.
- Ensure we only initiate a single build or have a max number of builds, if someone pushes multiple commits, we shouldn't test every commit (someone may push thousands, we can't build for each one). Ideally, we'd build checking the between the first and last commit.

**Comment by bradleyfalzon** [comment]
We'll need to also support sending an email notification to the user on failure, but it's not clear to me exactly how to get the user's permission. I presume only members of the user/organisation can push directly to a branch, and in which case I may or may not have access to their private email address.

**Comment by fortytw2** [comment]
Additionally, gopherCI seems to only build a PR on the first opening of it, not for subsequent commits on the same PR (not sure if I'm misreading this though)

**Comment by bradleyfalzon** [comment]
Yeah and I'm tracking that in https://github.com/bradleyfalzon/gopherci/issues/24 it's a really simple fix so will address soon.

**Comment by bradleyfalzon** [comment]
This is now being blocked by https://github.com/google/go-github/pull/533 but I don't think I'll have an implementation before that's merged in anyway.

**Comment by shurcooL** [comment]
> Note many people would push to their repository then make a PR, this workflow should ideally not cause GopherCI to run on push and then on PR creation.

Hehe, Travis does that and it's indeed suboptimal. But the fact they haven't resolved it makes me unsure if it's viable to solve it well (maybe it is, maybe it isn't).

Are you planning on using commit statuses to report CI result on pushed commits? I guess so based on google/go-github#533. That's what Travis does too, and I think it'll be great. Just wanted to give the approach a 👍.

**Comment by bradleyfalzon** [comment]
Correct, that's what the go-github PR is for, just working out how to best make https://github.com/bradleyfalzon/gopherci/blob/master/internal/github/handlers.go#L67 a little more generic (move to event method which accepts statuses url, analyser.config and installationID), so a small refactor is needed but I think it's all relatively straight forward.

To begin with, I'll just hit the statuses API and in the near future, we can organise email notifications (and other notifications customisation in general), but the first step is having us check the push request.
