### ISSUE TITLE
Summary for a single PR's result

### ISSUE THREAD

**Issue by bradleyfalzon** [bradleyfalzon/gopherci#28]
Not everyone wants comments on the PRs themselves, some checks are just noisy. We should support a summary view, either on a dedicated page or just as a PR comment.

Summary page should also support re-running build, for intermittent issues, help development of GopherCI (not having to send another PR each time), and possibly rerun tests if the base branch changes (but we should detect this as being discussed in #25)

See related #3, #17, #27

**Comment by bradleyfalzon** [comment]
Web UI deployed in #76.

**Comment by shurcooL** [comment]
If it's deployed, where can I see it?

**Comment by fortytw2** [comment]
I asked the same thing earlier -> https://gci.gopherci.io/analysis/18 is a live example, but there are more mockups/detailed views around, I think
