### ISSUE TITLE
Ignore vendored dependencies, or those ending with certain filenames

### ISSUE THREAD

**Issue by fortytw2** [bradleyfalzon/gopherci#57]
Would be lovely to have the option to ignore folders or file prefixes (i.e. `_generated.go`), so this https://github.com/fortytw2/hydrocarbon/pull/30 can be avoided in the future :smile:

**Comment by bradleyfalzon** [comment]
Yes agreed, there was a discussion on https://github.com/golang/go/issues/13560 about this to detected generated code. What are the conventions at the moment, or just make it configurable (always ignore files matching X regexp)?

**Comment by fortytw2** [comment]
I don't know if there are any great conventions right now - perhaps a combination of what `go-tools` does, with an optional "additional regexp filenames" would be sufficient?

**Comment by bradleyfalzon** [comment]
Yeah sgtm.

Relates #8

**Comment by shurcooL** [comment]
Until golang/go#13560 is resolved, there is no official standard. I created https://github.com/shurcooL/go/blob/978ecf0df5227d84eec040632ee76669b5a93619/analysis/generated_detection.go#L17 as a best effort solution until then.
