### ISSUE TITLE
Consider adding support for github.com/mvdan/unparam

### ISSUE THREAD

**Issue by bradleyfalzon** [bradleyfalzon/gopherci#68]
Review https://github.com/mvdan/unparam and determine whether there's any value in using unparam by default or just having it as an option.

Currently we're using https://github.com/dominikh/go-tools/tree/master/cmd/unused added in #47

**Comment by mvdan** [comment]
Note that the two are complementary - `unused` doesn't do parameters, and `unparam` doesn't do funcs/methods/types/vars/consts.

Also worth noting that `unparam`, by design, can't be free from false positives. It can be pretty darn close on regular code, though.

**Comment by bradleyfalzon** [comment]
Thanks @mvdan, I've run each tool against each other's testdata directories and I can see there are no duplicate errors.

So I see no concern running both tools right now, and I've already seen value in unparam myself.
