### ISSUE TITLE
Analyer's git diff can fail with insufficient history

### ISSUE THREAD

**Issue by bradleyfalzon** [bradleyfalzon/gopherci#79]
The analyser obtains a diff of the branch/ref to pass to revgrep, which uses it to filter issues to lines which have recently changed.

In the case of a push, the diff is generated using the head's ref and a relative number of commits. For example if the head ref is `abcd` and there's 5 commits being pushed, the diff is between `abcd~5` and `abcd`. We use relative numbers because the "before" diff might have been overwritten.

But this doesn't work in some scenarios, I believe it should fail for first time pushes (there is no history to diff), but also when a user (@fortytw2, I'm looking at you) pushes a branch to an existing repo but it doesn't have any shared history. 

It's likely that analyser just needs to check if the `baseRef` exists at the `baseURL`, and if so, do the diff as normal, if not, just do a `git show` on the `headRef` at the `headURL`.

**Comment by fortytw2** [comment]
Here's what Github shows in this failure mode ->
<img width="1074" alt="screen shot 2017-04-09 at 4 40 47 pm" src="https://cloud.githubusercontent.com/assets/10286538/24838190/53b4aebe-1d43-11e7-81d0-2e602ad89b3d.png">
