### ISSUE TITLE
Go get not working

### ISSUE THREAD

**Issue by klauern** [bradleyfalzon/gopherci#82]
I am trying to simply `go get` the repo, but it doesn't appear to be working.

```sh
✔ ~ 07:55 $ go get -u github.com/bradleyfalzon/gopherci
# cd /home/klauer/dev/go/src/github.com/bradleyfalzon/gopherci; git submodule update --init --recursive
fatal: No url found for submodule path 'vendor/github.com/dgrijalva/jwt-go' in .gitmodules
package github.com/bradleyfalzon/gopherci: exit status 128
```

**Comment by bradleyfalzon** [comment]
Sorry mate, it's an artifact when we were using git submodules for vendoring, hadn't removed them all. I'll switch to Go's dep once they merge the manifest/lock name changes.

This should be fixed, can you try again?

**Comment by klauern** [comment]
That appears to have done the trick!  Thanks much
