### ISSUE TITLE
Gracefully handle git clone errors

### ISSUE THREAD

**Issue by bradleyfalzon** [bradleyfalzon/gopherci#85]
GopherCI can sometimes have a failure in cloning the repo. It commonly happens when GopherCI runs after the branch has been removed or ref has been overwritten (force push).

In these cases GopherCI should probably still fail the build (eventually there may be a UI option to force build success), but with a more helpful error message instead of a generic internal error.

Relates to #88.

**Comment by bradleyfalzon** [comment]
@judwhite points out there should be some retry logic here too.

**Comment by bradleyfalzon** [comment]
This is mostly handled by #88 now, we fail the build and display the error. If we need more than this, we can open the issue again.

**Comment by judwhite** [comment]
@bradleyfalzon Wait until `git gc` and `git prune` do nothing to help you and your only option is `rm -rf` 😄

**Comment by bradleyfalzon** [comment]
Yeah I really don't have any experience with very large repositories. But to wrap https://github.com/bradleyfalzon/gopherci/blob/206139339832bb6a9377bd8ac0e8c81216895a0b/internal/analyser/cloner.go in a RetryCloner should be straight forward - if that's the issue you mean?
